# Generated by Django 2.0.3 on 2018-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=32, verbose_name='Ticker')),
                ('price_eur', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Price (eur)')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Price (usd)')),
                ('price_btc', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Price (btc)')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
