# Generated by Django 2.0.3 on 2018-03-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32, verbose_name='Ticker')),
                ('position', models.DecimalField(decimal_places=18, max_digits=27, verbose_name='Position')),
                ('target', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Target')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('ticker',)},
        ),
    ]
