# Generated by Django 2.0.3 on 2018-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Target (%)'),
        ),
    ]
